//! Request / response bodies. Binary fields are standard base64 (RFC 4648 §4,
//! with padding).

use serde::{Deserialize, Serialize};

use crate::backend::{KeyDescriptor, KeyType};

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct SignRequest {
    pub key_id: String,
    pub algorithm: String,
    /// Message to sign (base64). The service hashes it; send the message, not a digest.
    pub payload: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SignResponse {
    pub key_id: String,
    pub algorithm: String,
    /// Base64 signature. ECDSA: DER `Ecdsa-Sig-Value`; Ed25519: 64 bytes; RSA-PSS: modulus-sized.
    pub signature: String,
    /// Time spent in the key backend (queueing for a session + HSM call), in
    /// milliseconds with microsecond precision.
    pub duration_ms: f64,
}

/// Where a signature is verified.
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum Verifier {
    /// In the service, with the public key exported from the HSM (default).
    #[default]
    Software,
    /// Inside the HSM with `C_Verify`.
    Hsm,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct VerifyRequest {
    pub key_id: String,
    pub algorithm: String,
    pub payload: String,
    pub signature: String,
    #[serde(default)]
    pub verifier: Verifier,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct VerifyResponse {
    pub key_id: String,
    pub algorithm: String,
    pub valid: bool,
    pub verifier: Verifier,
    pub duration_ms: f64,
}

#[derive(Debug, Clone, Serialize)]
pub struct PublicKeyResponse {
    pub key_id: String,
    pub key_type: KeyType,
    pub algorithms: Vec<&'static str>,
    /// `-----BEGIN PUBLIC KEY-----` (SPKI) PEM.
    pub public_key_pem: String,
    /// Base64 of the DER SubjectPublicKeyInfo.
    pub public_key_der: String,
}

#[derive(Debug, Clone, Serialize)]
pub struct KeysResponse {
    pub keys: Vec<KeyDescriptor>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct EncryptRequest {
    pub key_id: String,
    pub plaintext: String,
    /// Optional additional authenticated data (base64): bound to the
    /// ciphertext but not encrypted.
    #[serde(default)]
    pub aad: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EncryptResponse {
    pub key_id: String,
    pub algorithm: String,
    /// 96-bit IV, freshly generated by the HSM for this message.
    pub iv: String,
    /// Ciphertext with the 128-bit GCM tag appended.
    pub ciphertext: String,
    pub duration_ms: f64,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct DecryptRequest {
    pub key_id: String,
    pub iv: String,
    pub ciphertext: String,
    #[serde(default)]
    pub aad: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DecryptResponse {
    pub key_id: String,
    pub plaintext: String,
    pub duration_ms: f64,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct EnvelopeEncryptRequest {
    pub wrapping_key_id: String,
    pub plaintext: String,
    #[serde(default)]
    pub aad: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EnvelopeEncryptResponse {
    pub wrapping_key_id: String,
    /// How the DEK is wrapped (`AES_KEY_WRAP_PAD`, RFC 5649).
    pub wrap_algorithm: String,
    /// The per-message DEK, encrypted under the wrapping key.
    pub wrapped_key: String,
    /// AEAD used with the DEK (`AES_256_GCM`).
    pub algorithm: String,
    pub iv: String,
    pub ciphertext: String,
    pub duration_ms: f64,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct EnvelopeDecryptRequest {
    pub wrapping_key_id: String,
    pub wrapped_key: String,
    pub iv: String,
    pub ciphertext: String,
    #[serde(default)]
    pub aad: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EnvelopeDecryptResponse {
    pub wrapping_key_id: String,
    pub plaintext: String,
    pub duration_ms: f64,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct HealthResponse {
    pub status: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub backend: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub error: Option<String>,
}
